site_name: Pici Documentation
repo_url: https://github.com/phihes/pici
extra_javascript:
  - extra/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - extra/peerinnovation.css
nav:
  - About Pici: index.md
  - Getting started: getting-started.md
  - Using the toolbox: usage.md
  - Examples: examples.md
  - Reference: reference/
theme:
  name: material
  palette:
    scheme: peerinnovation
  logo: images/logo_64px.png
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - toc.integrate
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Peer_Innovation
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
plugins:
- search
- gen-files:
    scripts:
      - docs/extra/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
    custom_templates: templates
    watch:
      - pici