site_name: PICI Peer Innovation Community Indicators
repo_url: https://github.com/phihes/pici
extra_javascript:
  - extra/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - extra/peerinnovation.css
nav:
  - About: index.md
  - Usage:
    - using.md
    - analyzing.md
    - extending.md
  - Examples:
    - examples.md
    - examples/Loading the toolbox.ipynb
    - examples/Creating a custom indicator.ipynb
  - Indicators: indicators.md
  - Code reference: reference/
theme:
  name: material
  palette:
    scheme: peerinnovation
  logo: images/logo_64px.png
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - navigation.sections
    - toc.integrate
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Peer_Innovation
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - toc:
      toc_depth: 3
plugins:
- search
- autorefs
- glightbox:
    touchNavigation: true
    loop: false
    effect: zoom
    width: 100%
    height: auto
    zoomable: true
    draggable: true
- mkdocs-jupyter:
    ignore: ["*.py"]
    include_source: True
    theme: solarizedl
- exclude:
    glob:
      - "*_depr.py"
      - tests/*
- gen-files:
    scripts:
      - docs/extra/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
    custom_templates: templates
    watch:
      - pici