name: mkdocs-gh-pages
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2.1.6
        with:
          path: deployer/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/mkdocs-gh-pages.yml') }}
      - run: pip install cdlib
      - run: pip install poetry
      - run: |
          cd deployer
          poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - run: mkdocs gh-deploy --force
